typography_spectrum: 0.11235195444896817
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.12132990569807589
  lightness: 0.9597804425284266
  saturation: 0.05415317486040294
  rhythmicContrast: 0.5346518417354673
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5067622021306306
analytics:
  google: null
  facebook: null
  twitter: null
name: Soyuz Digital
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Title
purpose: []
